services:
  salary-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    volumes:
      - ./data:/app/data  # Mount data directory for faster I/O
      - ./app.py:/app/app.py  # Mount app.py directly to reflect changes immediately
    restart: unless-stopped 