[theme]
primaryColor = "#00A651" # A vibrant green
backgroundColor = "#FFFFFF" # White
secondaryBackgroundColor = "#F0FAF5" # Light mint green
textColor = "#333333" # Dark gray
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = false 